title: Pedro Bernardino
logo: /img/logo.png
description: Arganil, Coimbra, Portugal<br>
[linkedin.com/in/pedro--bernardino](https://www.linkedin.com/in/pedro--bernardino/)<br>
[github.com/pedro-bernardino](https://github.com/pedro-bernardino)
#show_downloads: true
theme: jekyll-theme-minimal
